#!/usr/bin/env node

var program = require('commander');
var DB = require("./DB");

var db1, db2, all = {};
var db1Tip = '--db1=dbuser:dbpassword@dbhost~database#dbport';
var db2Tip = '--db2=dbuser:dbpassword@dbhost~database#dbport+sshuser:sshpassword@sshhost#sshport';
var typeTip = '--type=table|procedure|function|data';
var tableTip = '--table=db1table:db2table';

program
	.on('--help', function(){
		console.log('  实例:');
		console.log('');
		console.log('    mysqldiff --db1=root:password@127.0.0.1~database1 --db2=root:password@127.0.0.1~database2');
		console.log('');
	})
	.version('0.0.1')
	.description('mysql 数据库表结构，存储过程，函数，表数据对比工具，差异生成SQL。')
	.option('--db1 <server>', db1Tip)
	.option('--db2 <server>', db2Tip)
	.option('--type <type>', typeTip)
	.option('--table <table>', tableTip)
	.option('--reverse', '交换db1与db2配置')
	.parse(process.argv);

function check() {
	if (!program.db1 || program.db1.indexOf(':') == -1 || program.db1.indexOf('@') == -1 || program.db1.indexOf('~') == -1) return console.log('--db1 参数错误！', db1Tip);
	if (!program.db2 || program.db2.indexOf(':') == -1 || program.db2.indexOf('@') == -1 || program.db2.indexOf('~') == -1) return console.log('--db2 参数错误！', db2Tip);
	if (program.type && !/^(table|procedure|function|data)$/i.test(program.type)) return console.log('--type 参数错误！', typeTip);
	if (program.type == 'data' && !program.table) return console.log('--table 参数错误！', tableTip);
	return true;
}
function start() {
	if (!check()) return;
	console.log('-- 正在连接数据库：db1 & db2...');
	db1 = new DB(program.reverse ? program.db2 : program.db1);
	db2 = new DB(program.reverse ? program.db1 : program.db2);
	db1.connect().then(function(v){
		if (!v) return console.log('-- 数据库db1：连接成功！');
		console.error('数据库db1连接失败：', v.message);
		exit();
	}).then(db2.connect).then(function(v){
		if (v) console.error('-- 数据库db2连接失败：', v.message);
		else console.log('-- 数据库db2：连接成功！');
		if (v) exit();
		Promise.all([getTables(), getParameters(), getDatas()]).then(allDesc).then(diff).then(function(v) {
			if (v.sqlUp && (program.type == 'table' || !program.type)) {
				console.log('-- 数据库db2需要更新表结构如下：');
				for(var k in v.sql) console.log(v.sql[k]);
			}
			if (v.procUp && (program.type == 'procedure' || !program.type)) {
				console.log('-- 数据库db2需要更新存储过程如下：');
				for(var k in v.proc) console.log(v.proc[k]);
			}
			if (v.funcUp && (program.type == 'function' || !program.type)) {
				console.log('-- 数据库db2需要更新函数如下：');
				for(var k in v.func) console.log(v.func[k]);
			}
			if (v.dataUp && program.type && program.type == 'data') {
				console.log('-- 数据库db2需要更新数据如下：');
				for(var k in v.data) console.log(v.data[k]);
			}
			if (!v.sqlUp && !v.procUp && !v.funcUp && !v.dataUp) console.log('-- 已经是最新，不需要更新！');
			exit();
		});
	});
}
function diff(v) {
	var d = { sql: {}, proc: {}, func: {}, data: {}, sqlUp: 0, procUp: 0, funcUp: 0, dataUp: 0 };
	if (program.type == 'table' || !program.type) for(var i = 0, len = v[0][0].length; i < len; i++) {
		var name = v[0][0][i];
		var table1 = v[2][name];
		var table2 = v[3][name];
		var sql = diffTable(name, table1, table2);
		if (sql && sql.length > 0) {
			d.sql[name] = sql;
			d.sqlUp = 1;
		}
	}
	if (program.type == 'procedure' || !program.type) for(var i = 0, len = v[1][0].length; i < len; i++) {
		var name = v[1][0][i];
		var proc1 = v[2][name];
		var proc2 = v[3][name];
		var sql = diffProcedure(name, proc1, proc2, 'PROCEDURE');
		if (sql && sql.length > 0) {
			d.proc[name] = sql;
			d.procUp = 1;
		}
	}
	if (program.type == 'function' || !program.type) for(var i = 0, len = v[1][1].length; i < len; i++) {
		var name = v[1][1][i];
		var proc1 = v[2][name];
		var proc2 = v[3][name];
		var sql = diffProcedure(name, proc1, proc2, 'FUNCTION');
		if (sql && sql.length > 0) {
			d.func[name] = sql;
			d.funcUp = 1;
		}
	}
	if (program.type && program.type == 'data') {
		var pk1 = getTablePK(v[2][v[2].table1]);
		var pk2 = getTablePK(v[3][v[2].table2]);
		if (pk1 == pk2) {
			var sql = diffData(v[2][0], v[2][1], pk1.split(','), v[2].table1);
			if (sql && sql.length > 0) {
				d.data[name] = sql;
				d.dataUp = 1;
			}
		}
	}
	return Promise.resolve(d);
}
function addslashes(str) {
	return (str + '').replace(/[\\"']/g, '\\$&').replace(/\u0000/g, '\\0')
}
function diffData(v1, v2, pk, table) {
	var v = [[],{},{}];
	for(var i=0; i<v1.length; i++) {
		var o = v1[i], k = getDataPKV(o, pk);
		if (v[0].indexOf(k) == -1) v[0].push(k);
		v[1][k] = o;
	}
	for(var i=0; i<v2.length; i++) {
		var o = v2[i], k = getDataPKV(o, pk);
		if (v[0].indexOf(k) == -1) v[0].push(k);
		v[2][k] = o;
	}
	var inserts = [], deletes = [], updates = [];
	for(var i = 0, len = v[0].length; i < len; i++) {
		var name = v[0][i];
		var d1 = v[1][name];
		var d2 = v[2][name];

		if (d1 && !d2) { inserts.push(d1); continue; }
		if (!d1 && d2) { deletes.push(d2); continue; }

		updates.push(name);
	}
	var sql = '';
	if (inserts.length > 0) {
		var insertSql = 'INSERT INTO `'+table+'` VALUES';
		for(var i = 0, len = inserts.length; i < len; i++) {
			insertSql += '(';
			for(var k in inserts[i]) {
				var oo = inserts[i][k];
				insertSql +=  (typeof oo === 'string' ? ('\''+addslashes(oo)+'\'') : oo) + ',';
			}
			insertSql = insertSql.substring(0, insertSql.length-1);
			insertSql += '),';
		}
		insertSql = insertSql.substring(0, insertSql.length-1);
		insertSql += ';\n';
		sql += insertSql;
	}
	if (deletes.length > 0) {
		for(var i = 0, len = deletes.length; i < len; i++) {
			var deleteSql = 'DELETE FROM `'+table+'` WHERE 1';
			var oo = deletes[i];
			for(var j in pk) {
				deleteSql += ' and `'+pk[j]+'`='+(typeof oo[pk[j]] === 'string' ? ('\''+addslashes(oo[pk[j]])+'\'') : oo[pk[j]]);
			}
			deleteSql += ';\n';
			sql += deleteSql.replace(' WHERE 1 and ', ' WHERE ');
		}
	}
	if (updates.length > 0) {
		for(var i = 0, len = updates.length; i < len; i++) {
			var updateSql = 'UPDATE `'+table+'` SET ', upS = '';
			for(var j in v[1][updates[i]]) {
				var oo = v[1][updates[i]][j];
				if (oo == v[2][updates[i]][j]) continue;
				upS += '`'+j+'`='+(typeof oo === 'string' ? ('\''+addslashes(oo)+'\'') : oo)+',';
			}
			if (upS.length == 0) continue;
			updateSql += upS.substring(0, upS.length - 1) + ' WHERE 1';
			var oo = v[2][updates[i]];
			for(var j in pk) {
				updateSql += ' and `'+pk[j]+'`='+(typeof oo[pk[j]] === 'string' ? ('\''+addslashes(oo[pk[j]])+'\'') : oo[pk[j]]);
			}
			updateSql += ';\n';
			sql += updateSql.replace(' WHERE 1 and ', ' WHERE ');
		}
	}
	return sql;
}
function getDataPKV(obj, pk) {
	var v = '';
	for(var i=0;i<pk.length; i++) v += obj[pk[i]] + '\0';
	return v ? v.substring(0, v.length - 1) : v;
}
function getTablePK(table) {
	var line = table.match(/PRIMARY KEY \(.*\)/i)[0];
	var pk = line.match(/`.*`/i)[0].replace(/`/g, '');
	return pk;
}
function diffProcedure(name, proc1, proc2, ex) {
	var p1 = filterProcedure(proc1);
	var p2 = filterProcedure(proc2);
	if (p1 == p2) return null;

	if (p1 != '' && p2 == '') return 'DELIMITER ;;\n'+changeProcedure(proc1, proc2)+' ;;\nDELIMITER ;\n';
	if (p1 == '' && p2 != '') return 'DROP '+ex+' `' + name + '`;\n';

	return 'DROP '+ex+' `' + name + '`;\nDELIMITER ;;\n'+changeProcedure(proc1, proc2)+' ;;\nDELIMITER ;\n';
}
function changeProcedure(proc1, proc2) {
	if (!proc2) {
		var user = db2.getUser();
		proc1 = proc1.replace(/ DEFINER=`.*`@/g, ' DEFINER=`'+user+'`@');
		return proc1;
	}
	var definer = proc2.match(/ DEFINER=(`.*`@`.*`) /i)[1];
	proc1 = proc1.replace(/ DEFINER=(`.*`@`.*`) /g, ' DEFINER='+definer+' ');
	return proc1;
}
function filterProcedure(proc) {
	if (!proc) return '';
	proc = proc.replace(/ DEFINER=.* FUNCTION/g, ' FUNCTION');
	proc = proc.replace(/ DEFINER=.* PROCEDURE/g, ' PROCEDURE');
	return proc.trim();
}
function diffTable(name, table1, table2) {
	var t1 = filterTable(table1);
	var t2 = filterTable(table2);
	if (t1 == t2) return null;

	if (t1 != '' && t2 == '') return table1 + ';\n';
	if (t1 == '' && t2 != '') return 'DROP TABLE `' + name + '`;\n';

	return diffTableField(name, table1, table2);
}
function diffTableField(name, table1, table2) {
	var t1 = table1.split('\n');
	var t2 = table2.split('\n');
	if (t1.length < 3 || t2.length < 3) return '';

	var col = [], col1 = {}, col2 = {};
	var key = [], key1 = {}, key2 = {};
	var pk1 = '', pk2 = '';

	for (var i=1, len = t1.length-1; i<len; i++) {
		var row = t1[i].trim(), l = row.length-1;
		if (row.lastIndexOf(',') == l) row = row.substring(0, l);
		var field = row.indexOf('`') == 0 ? row.split(' ')[0] : false;
		var pkey = row.indexOf('PRIMARY KEY ') == 0 ? row.substring(12) : false;
		var ikey = row.indexOf('KEY `') == 0 ? row.substring(4) : false;
		if (field) { col1[field] = row; if (col.indexOf(field) == -1) col.push(field); }
		if (pkey) pk1 = pkey;
		if (ikey) { key1[ikey] = 1; if (key.indexOf(ikey) == -1) key.push(ikey); }
	}

	for (var i=1, len = t2.length-1; i<len; i++) {
		var row = t2[i].trim(), l = row.length-1;
		if (row.lastIndexOf(',') == l) row = row.substring(0, l);
		var field = row.indexOf('`') == 0 ? row.split(' ')[0] : false;
		var pkey = row.indexOf('PRIMARY KEY ') == 0 ? row.substring(12) : false;
		var ikey = row.indexOf('KEY `') == 0 ? row.substring(4) : false;
		if (field) { col2[field] = row; if (col.indexOf(field) == -1) col.push(field); }
		if (pkey) pk2 = pkey;
		if (ikey) { key2[ikey] = 1; if (key.indexOf(ikey) == -1) key.push(ikey); }
	}

	var sql = '';
	for(var i=0, len = col.length; i<len; i++) {
		var c = col[i], c1 = col1[c], c2 = col2[c];
		var c3 = filterField(c1), c4 = filterField(c2);
		if (c3 == c4) continue;

		if (c3 != '' && c4 == '') {
			sql += 'ALTER TABLE `'+name+'` ADD COLUMN '+c1+';\n';
			continue;
		}
		if (c3 == '' && c4 != '') {
			sql += 'ALTER TABLE `'+name+'` DROP COLUMN '+c+';\n';
			continue;
		}
		sql += 'ALTER TABLE `'+name+'` CHANGE COLUMN '+c+' '+c1+';\n';
	}

	if (pk1 != '' && pk2 == '') sql += 'ALTER TABLE `'+name+'` ADD PRIMARY KEY '+pk1+';\n';
	if (pk1 == '' && pk2 != '') sql += 'ALTER TABLE `'+name+'` DROP PRIMARY KEY;\n';
	if (pk1 != '' && pk2 != '' && pk1 != pk2) sql += 'ALTER TABLE `'+name+'` DROP PRIMARY KEY,ADD PRIMARY KEY '+pk2+';\n';

	for(var i=0, len = key.length; i<len; i++) {
		var k = key[i], k1 = key1[k], k2 = key2[k];
		if (k1 == k2) continue;

		if (k1 && !k2) {
			sql += 'ALTER TABLE `'+name+'` ADD INDEX '+k+';\n';
			continue;
		}
		if (!k1 && k2) {
			var kname = k.split(' ')[0];
			sql += 'ALTER TABLE `'+name+'` DROP INDEX '+kname+';\n';
			continue;
		}
	}

	return sql;
}
function filterField(field) {
	if (!field) return '';
	field = field.replace(/ COMMENT '.*'/g, '');
	field = field.replace(/ COMMENT='.*'/g, '');
	return field.trim();
}
function filterTable(table) {
	if (!table) return '';
	table = table.replace(/AUTO_INCREMENT=.* /g, '');
	table = table.replace(/ CHECKSUM=1/g, '');
	table = table.replace(/ DELAY_KEY_WRITE=1/g, '');
	table = table.replace(/ ROW_FORMAT=DYNAMIC/g, '');
	table = table.replace(/ DEFAULT/g, '');
	table = filterField(table);
	return table.trim();
}
function allDesc(v) {
	console.log('-- 开始比较db1 & db2的差异...');
	var list = [], objs = [];
	if (program.type == 'table' || !program.type) for(var k in v[0][1]) {
		list.push(db1.showCreateTable(k));
		objs.push('0-' + 1 + '-' + k);
	}
	if (program.type == 'table' || !program.type) for(var k in v[0][2]) {
		list.push(db2.showCreateTable(k));
		objs.push('1-' + 1 + '-' + k);
	}
	if (program.type == 'procedure' || program.type == 'function' || !program.type) for(var k in v[1][2]) {
		var proc = v[1][0].indexOf(k) != -1;
		var func = v[1][1].indexOf(k) != -1;
		if (proc) {
			list.push(db1.showCreateProcedure(k));
			objs.push('0-' + 2 + '-' + k);
		}
		if (func) {
			list.push(db1.showCreateFunction(k));
			objs.push('0-' + 3 + '-' + k);
		}
	}
	if (program.type == 'procedure' || program.type == 'function' || !program.type) for(var k in v[1][3]) {
		var proc = v[1][0].indexOf(k) != -1;
		var func = v[1][1].indexOf(k) != -1;
		if (proc) {
			list.push(db2.showCreateProcedure(k));
			objs.push('1-' + 2 + '-' + k);
		}
		if (func) {
			list.push(db2.showCreateFunction(k));
			objs.push('1-' + 3 + '-' + k);
		}
	}
	if (program.type && program.type == 'data') {
		list.push(db1.showCreateTable(v[2].table1));
		objs.push('0-' + 1 + '-' + v[2].table1);
		list.push(db2.showCreateTable(v[2].table2));
		objs.push('1-' + 1 + '-' + v[2].table2);
	}
	return Promise.all(list).then(function(v2){
		v.push({}); v.push({});
		for(var i = 0, len = v2.length; i < len; i++) {
			var types = objs[i].split('-');
			var val = v2[i];
			var s = parseInt(types[0]) + 2;
			v[s][types[2]] = val;
		}
		return v;
	});
}
function getDatas() {
	var data = [[], []];
	if (!program.type || (program.type && program.type != 'data')) return Promise.resolve(data);
	var tables = program.table.split(':');
	var table1 = tables[0];
	var table2 = tables.length == 2 ? tables[1] : table1;
	return Promise.all([db1.getData(table1), db2.getData(table2)]).then(function(v){
		data[0] = v[0];
		data[1] = v[1];
		data.table1 = table1;
		data.table2 = table2;
		return data;
	});
}
function getTables() {
	var tables = [[], {}, {}];
	if (program.type && program.type != 'table') return Promise.resolve(tables);
	console.log('-- 正在获取数据表...');
	return Promise.all([db1.tables(), db2.tables()]).then(function(v){
		for(var i = 0, len = v[0].length; i < len; i++) {
			var table = v[0][i].tabName;
			tables[0].push(table);
			tables[1][table] = {};
		}
		console.log('-- db1获取数据表', v[0].length, '个！');
		for(var i = 0, len = v[1].length; i < len; i++) {
			var table = v[1][i].tabName;
			if (tables[0].indexOf(table) == -1) tables[0].push(table);
			tables[2][table] = {};
		}
		tables[0].sort();
		console.log('-- db2获取数据表', v[1].length, '个！');
		console.log('-- db1 & db2 合并数据表', tables[0].length, '个！');
		return tables;
	});
}
function getParameters() {
	var parameters = [[], [], {}, {}];
	if (program.type && program.type != 'procedure' && program.type != 'function') return Promise.resolve(parameters);
	console.log('-- 正在获取存储过程和函数...');
	return Promise.all([db1.parameters(), db2.parameters()]).then(function(v){
		for(var i = 0, len = v[0].length; i < len; i++) {
			var parameter = v[0][i].parName;
			var type = v[0][i].type;
			if (type == 'PROCEDURE') parameters[0].push(parameter);
			if (type == 'FUNCTION')  parameters[1].push(parameter);
			parameters[2][parameter] = {};
		}
		console.log('-- db1获取存储过程和函数', v[0].length, '个！');
		for(var i = 0, len = v[1].length; i < len; i++) {
			var parameter = v[1][i].parName;
			var type = v[1][i].type;
			if (type == 'PROCEDURE' && parameters[0].indexOf(parameter) == -1)
				parameters[0].push(parameter);
			if (type == 'FUNCTION' && parameters[1].indexOf(parameter) == -1)
				parameters[1].push(parameter);
			parameters[3][parameter] = {};
		}
		console.log('-- db2获取存储过程和函数', v[1].length, '个！');
		console.log('-- db1 & db2 合并存储过程', parameters[0].length, '个！');
		console.log('-- db1 & db2 合并函数', parameters[1].length, '个！');
		return parameters;
	});
}

function exit() {
	if (!db1 && !db2) process.exit();
	var list = [];
	if (db1) list.push(db1.close());
	if (db2) list.push(db2.close());
	Promise.all(list).then(function(v){
		setTimeout(process.exit, 1000);
	})
}

start();